//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronics_Store.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model_Specification
    {
        public int ID { get; set; }
        public Nullable<int> Model_FK { get; set; }
        public string Model_name { get; set; }
        public string Specification { get; set; }
        public Nullable<System.DateTime> Date_of_manufacture { get; set; }
        public Nullable<int> Available_in_stock { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Model Model { get; set; }
    }
}
