//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronics_Store.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public int ID { get; set; }
        public Nullable<int> Category_name_FK { get; set; }
        public Nullable<int> Manufacturer_name_FK { get; set; }
        public string Model1 { get; set; }
        public Nullable<int> Model_specification_FK { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Model_Specification Model_Specification { get; set; }
    }
}
