//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronics_Store.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Personal_Data
    {
        public int ID { get; set; }
        public Nullable<int> User_FK { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Current_city { get; set; }
        public string E_mail { get; set; }
        public string Role { get; set; }
    
        public virtual User User { get; set; }
    }
}
